# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/live/vpc"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Asia/Tel_Aviv"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all"

  - package-ecosystem: "terraform"
    directory: "/live/eks"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Asia/Tel_Aviv"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all"

  - package-ecosystem: "terraform"
    directory: "/modules/vpc"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Asia/Tel_Aviv"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all"

  - package-ecosystem: "terraform"
    directory: "/modules/eks"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Asia/Tel_Aviv"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all"
