apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: services
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: Never
  limits:
    cpu: 200
    memory: 300Gi
  template:
    metadata:
      labels:
        nodePool: services
    spec:
      nodeClassRef:
        name: main
      requirements:
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values:
            - c
            - d
            - g
            - i
            - m
            - p
            - r
            - x
            - z
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values:
            - '2'
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
            - spot
        - key: node.kubernetes.io/instance-type
          operator: NotIn
          values:
            - r4.large
            - r4.xlarge
            - r4.2xlarge
            - r4.4xlarge
            - r4.8xlarge
            - r4.16xlarge
            - m4.large
            - m4.xlarge
            - m4.2xlarge
            - m4.4xlarge
            - m4.10xlarge
            - m4.16xlarge
            - m5.4xlarge
            - m5a.4xlarge
            - m5a.8xlarge
            - m5a.12xlarge
            - m5a.16xlarge
            - m5a.24xlarge
            - m5ad.4xlarge
            - m5ad.8xlarge
            - m5ad.12xlarge
            - m5ad.16xlarge
            - m5ad.24xlarge
            - r5a.16xlarge
            - r5ad.16xlarge
            - r5a.24xlarge
            - r5ad.24xlarge
      startupTaints:
        - effect: NoExecute
          key: ebs.csi.aws.com/agent-not-ready
      taints:
        - effect: NoSchedule
          key: nodePool
          value: services
